version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: jampackd_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
    networks:
      - app_network

  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network: