version: '3.8'










volumes:
  accounts:
    external: true
  music:
    external: true

services:
  mongo:
    image: mongo:5
    volumes:
      - accounts:/data/db
      - music:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  accounts:
    build:
      context: accounts
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./accounts:/app
    environment:
      SIGNING_KEY: admin
      DATABASE_URL: mongodb://admin:admin@mongo
      MONGOHOST: mongo
      MONGODATABASE_ACCOUNTS: accounts
      MONGOUSER: admin
      MONGOPASSWORD: admin
      # WAIT_HOSTS: mongo:27017

  music:
    build:
      context: music
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./music:/app
    environment:
      DATABASE_URL: mongodb://admin:admin@mongo
      MONGOHOST: mongo
      MONGODATABASE_MUSIC: music
      MONGOUSER: admin
      MONGOPASSWORD: admin
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      USER: ${USER}
      SIGNING_KEY: admin

  ghi:
    build:
      context: ghi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_accounts: http://accounts:8000
      REACT_APP_MUSIC: http://music:8000
      REACT_APP_THIRD_PARTY_SERVICE: https://api.spotify.com
    depends_on:
      - accounts
      - music

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo/
    restart: always
