version: '3.8'

services:
  accounts:
    build: ./accounts
    ports:
      - "8000:8000"
    volumes:
      - accounts-data:/app/accounts/data
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:8081/accounts

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - mongodb-data:/data/db

volumes:
  accounts-data:
  mongodb-data: